channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - pip=23.0.1
  - tqdm=4.64.0
  - numpy=1.24.3
  - pandas=1.3.5
  - matplotlib=3.5.0
  # === torch installation ===
  - pytorch::torchaudio==0.12.1
  - pytorch::torchvision==0.13.1
  - pytorch::pytorch==1.12.1
  # 1. for cpuonly
  - pytorch::cpuonly
  # 2. or for cuda 11.6
  # - conda-forge::cudatoolkit=11.6
  # 3. or for cuda 11.3
  # - pytorch::cudatoolkit=11.3
  # 4. or for cuda 10.2
  # - pytorch::cudatoolkit=10.2
  - pip:
      - ruamel-yaml==0.17.21
      - ruamel-yaml-clib==0.2.7
      - learn2learn==0.1.7
      - gdown==4.7.1 # only to download large files from google drive
