name: meta-sampling
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.8
  - pip=23.0.1
  - tqdm=4.64.0
  - numpy=1.24.3
  - pandas=1.3.5
  - matplotlib=3.5.0
  - torchaudio==0.12.1
  - torchvision==0.13.1
  - pytorch==1.12.1
  - pip:
      - ruamel-yaml==0.17.21
      - ruamel-yaml-clib==0.2.7
      - learn2learn==0.1.7
